### ISSUE TITLE
chart saving

### ISSUE THREAD

**Issue by TheRealFowluhh** [kviks/Psych-Engine-Android#25]
### What is your question?

hi, i was wondering how to save the chart json on android... how? is it possible?

**Comment by Fixthebug307** [comment]
Yes, it's possible.

-Save your chart
 
-then load auto-save
 
-Your chart will automatically save on your clipboard.
 
-Create a file for example, "[your_chart_name].json"
 
-Now paste your chart from the json files
 
-Done

**Comment by TheRealFowluhh** [comment]
thanks

berry much
