### ISSUE TITLE
Mod folder isnt working

### ISSUE THREAD

**Issue by woaa12** [kviks/Psych-Engine-Android#3]
### Bug report

Anything added into the mod folder isn't read. Do i have to add it into the assets folder or nah? Will this get fixed?

**Comment by KlavierGayming** [comment]
no shit sherlock

**Comment by KlavierGayming** [comment]
dont put it into assets
wait till we fix it

**Comment by woaa12** [comment]
> dont put it into assets wait till we fix it

K lol
