### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Sanscode1937** [kviks/Psych-Engine-Android#6]
### Bug report

it's said C:/HaxeToolkit/haxe/lib/flixel/4,10,0/flixel/input/actions/FlxAction.hx:141: characters 18-46 : Type not found : FlxActionInputDigitalAndroid Please help

### Did you edit anything? If so, mention or summarize your changes.

no

**Comment by kviks** [comment]
haxelib install flixel 4.9.0
haxelib install flixel-addons 2.10.0
haxelib install flixel-demos 2.7.4
haxelib install flixel-templates 2.6.6
haxelib install flixel-ui 2.3.3
haxelib install flixel-tools 1.5.1
haxelib set flixel 4.9.0
haxelib set flixel-addons 2.10.0
haxelib set flixel-demos 2.7.4
haxelib set flixel-templates 2.6.6
haxelib set flixel-ui 2.3.3
haxelib set flixel-tools 1.5.1
